include:
  - ./docker-compose.dependencies.yml
  - ./docker-compose.backend.yml
  - ./docker-compose.monitoring.yml

networks:
  app-network:
    driver: bridge


volumes:
  redis:
  redis-config:
  prometheus-data:
  grafana-data:
