global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # WebSocket Server instances
  - job_name: 'websocket-server'
    metrics_path: '/metrics/'
    static_configs:
      - targets:
          # - 'websocket-server-1:8000'
          # - 'websocket-server-2:8000'
          - 'host.docker.internal:8000'
        labels:
          service: 'websocket-server'

  # AI Consumer
  - job_name: 'ai-consumer'
    metrics_path: '/metrics/'
    static_configs:
      - targets:
          # - 'ai-consumer:8000'
          - 'host.docker.internal:8002'
        labels:
          service: 'ai-consumer'

  # Message Relay
  - job_name: 'message-relay'
    metrics_path: '/metrics/'
    static_configs:
      - targets:
          # - 'message-relay:8001'
          - 'host.docker.internal:8001'
        labels:
          service: 'message-relay'
